In [1]:
import pandas as pd
import geopandas as gp
import numpy as np

## Muni bus stop data

In [72]:
path = '/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/Final Project/'
stops = pd.read_csv('/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/Final Project/google_transit/stops.txt')
shapes = pd.read_csv('/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/Final Project/google_transit/shapes.txt')
routes = pd.read_csv('/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/Final Project/google_transit/routes.txt')
stop_times = pd.read_csv('/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/Final Project/google_transit/stop_times.txt')
trips = pd.read_csv('/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/Final Project/google_transit/trips.txt')

In [61]:
trips_and_shapes = trips.merge(shapes, how='inner', left_on='shape_id', right_on='shape_id')
trips_shapes_routes = trips_and_shapes.merge(routes, how='left', left_on='route_id', right_on='route_id')
trips_shapes_routes.head()

,route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id,shape_pt_lon,shape_pt_lat,shape_pt_sequence,shape_dist_traveled
0,13392,1,8318856,Geary + 33rd Avenue,0,122,159274,-122.396968,37.795436,1,0
1,13392,1,8318856,Geary + 33rd Avenue,0,122,159274,-122.396784,37.795471,2,17
2,13392,1,8318856,Geary + 33rd Avenue,0,122,159274,-122.396598,37.794593,3,116
3,13392,1,8318856,Geary + 33rd Avenue,0,122,159274,-122.397809,37.794439,4,224
4,13392,1,8318856,Geary + 33rd Avenue,0,122,159274,-122.398983,37.794289,5,329

In [64]:
# trips_shapes_routes.head().to_csv("trips_shapes_routes.csv") #need to try and figure out which ones are frequent

## Commutter Shuttle Program Data

In [74]:
commuter_program_shuttles = gp.read_file(path+'MTA.speedbumps/geo_export_e2840cb2-6482-4a2f-bd56-0878a2cbccf3.shp')
commuter_program_shuttles

,cnn,date_creat,time_creat,created_us,from_st,date_last_,time_last_,last_edite,date_mtab_,time_mtab_,mtab_motio,mtab_reso_,objectid,status,streetname,to_st,workorder,geometry
0,10792000.0,None,None,None,16TH ST,None,None,None,None,None,None,None,48.0,None,PROSPER ST,17TH ST,None,POINT (-122.431645756432 37.763622580921)
1,3760101.0,None,None,None,HUDSON AVE,None,None,None,None,None,None,None,11.0,None,CASHMERE ST,CASHMERE ST END,None,POINT (-122.382957235907 37.735744935444)
2,2958000.0,None,None,None,HUDSON AVE,None,None,None,None,None,None,None,8.0,None,BERTHA LN,HARBOR RD,None,POINT (-122.381188030573 37.733369713131)
3,10970201.0,None,None,None,HUDSON AVE,None,None,None,None,None,None,None,49.0,None,REUEL CT,REUEL CT END,None,POINT (-122.383074321058 37.736501775361)
4,7002000.0,None,None,None,PARK ST,None,None,None,None,None,None,None,32.0,None,HOLLY PARK CIR,HIGHLAND AVE,None,POINT (-122.418862411824 37.737045357212)