In [1]:
import pandas as pd
import geopandas as gp
import numpy as np
import time
import censusgeocode as cg

## Muni bus stop data

In [2]:
muni_path = '/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/evictionmodel_190final/google_transit/'
stops = pd.read_csv(muni_path+ 'stops.txt')
shapes = pd.read_csv(muni_path+ 'shapes.txt')
routes = pd.read_csv(muni_path+ 'routes.txt')
stop_times = pd.read_csv(muni_path + 'stop_times.txt')
trips = pd.read_csv(muni_path +'trips.txt')

In [36]:
trips_and_shapes = trips.merge(shapes, how='inner', left_on='shape_id', right_on='shape_id')
trips_shapes_routes = trips_and_shapes.merge(routes, how='left', left_on='route_id', right_on='route_id')
#len(trips_shapes_routes) #try filtering by R and X- these are rapid and express routes

In [21]:
trips_shapes_routes_X = trips_shapes_routes[trips_shapes_routes["route_long_name"].str.contains("X")]
trips_shapes_routes_XR = trips_shapes_routes_X[trips_shapes_routes_X["route_long_name"].str.contains("R")]
len(trips_shapes_routes_XR)

107034

# Ping FCC API to geocode census tracts

In [4]:
def getGeoid(lon, lat):
#pings the FCC API to geocode lat lon coordinates to other geograpies.
    try:
        result = cg.coordinates(lon, lat)
        geoid = result['Census Tracts'][0]['GEOID']
        return geoid
    except(ValueError, TypeError):
        return 'Nan'

In [39]:
start = time.time()
stops["Geoid"] = stops.apply(lambda row: getGeoid(row["stop_lon"], row["stop_lat"]), axis=1)

end = time.time()
elapsed = end-start #should take about an hour
elapsed

3730.773733139038

In [40]:
stops.to_csv("data/geocoded_muni_stops.csv")

In [46]:
stops_grouped = stops.groupby("Geoid").count()
stops_grouped["num stops"] = stops_grouped["stop_id"]
stops_grouped = stops_grouped["num stops"]

# Group by Census Tract to count stops per tract

In [53]:
stops_grouped.to_csv("data/geocoded_muni_stops_bytract.csv")

## Commutter Shuttle Program Data

In [81]:
shuttle_path = '/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/evictionmodel_190final/MTA.speedbumps/'

commuter_program_shuttles = gp.read_file(shuttle_path+ 'geo_export_e2840cb2-6482-4a2f-bd56-0878a2cbccf3.shp')
len(commuter_program_shuttles)

52

In [82]:
commuter_program_shuttles["Location"] = commuter_program_shuttles["geometry"].astype(str).apply(lambda row: row.split("(")[1])
commuter_program_shuttles["Latitude"] = commuter_program_shuttles["Location"].astype(str).apply(lambda row: row.split(" ")[1][:-1])
commuter_program_shuttles["Longitude"] = commuter_program_shuttles["Location"].astype(str).apply(lambda row: row.split(" ")[0])

In [85]:
start = time.time()
commuter_program_shuttles["Geoid"] = commuter_program_shuttles.apply(lambda row: getGeoid(row["Longitude"], row["Latitude"]), axis=1)
# foo = commuter_program_shuttles.head(10).apply(lambda row: getGeoid(row["Longitude"], row["Latitude"]), axis=1)

end = time.time()
elapsed = end-start #should take about a minute
elapsed

65.00685691833496

In [86]:
commuter_program_shuttles = commuter_program_shuttles[['Geoid','from_st', 'to_st', 'geometry', 'Latitude', 'Longitude']]
commuter_program_shuttles.to_csv("/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/evictionmodel_190final/data/shuttles_geocodedbytract.csv")

In [48]:
commuter_program_shuttles

,cnn,date_creat,time_creat,created_us,from_st,date_last_,time_last_,last_edite,date_mtab_,time_mtab_,mtab_motio,mtab_reso_,objectid,status,streetname,to_st,workorder,geometry
0,10792000.0,None,None,None,16TH ST,None,None,None,None,None,None,None,48.0,None,PROSPER ST,17TH ST,None,POINT (-122.431645756432 37.763622580921)
1,3760101.0,None,None,None,HUDSON AVE,None,None,None,None,None,None,None,11.0,None,CASHMERE ST,CASHMERE ST END,None,POINT (-122.382957235907 37.735744935444)
2,2958000.0,None,None,None,HUDSON AVE,None,None,None,None,None,None,None,8.0,None,BERTHA LN,HARBOR RD,None,POINT (-122.381188030573 37.733369713131)
3,10970201.0,None,None,None,HUDSON AVE,None,None,None,None,None,None,None,49.0,None,REUEL CT,REUEL CT END,None,POINT (-122.383074321058 37.736501775361)
4,7002000.0,None,None,None,PARK ST,None,None,None,None,None,None,None,32.0,None,HOLLY PARK CIR,HIGHLAND AVE,None,POINT (-122.418862411824 37.737045357212)
5,5383000.0,None,None,None,23RD ST,None,None,None,None,None,None,None,28.0,None,FAIR OAKS ST,24TH ST,None,POINT (-122.424052576601 37.752465004481)
6,4672000.0,None,None,None,ENCLINE CT,None,None,None,None,None,None,None,19.0,None,DEL VALE AVE,OSHAUGHNESSY BLVD,None,POINT (-122.446441880416 37.740996970684)
7,7892000.0,None,None,None,MENDELL ST,None,None,None,None,None,None,None,37.0,None,KIRKWOOD AVE,KIRWOOD AVE END,None,POINT (-122.38778636602 37.736974692014)
8,2861000.0,None,None,None,MIGUEL ST,None,None,None,None,None,None,None,7.0,None,BEACON ST,DIAMOND ST,None,POINT (-122.43148843164 37.739477273506)
9,5382000.0,None,None,None,22ND ST,None,None,None,None,None,None,None,25.0,None,FAIR OAKS ST,23RD ST,None,POINT (-122.424259375988 37.754655570862)
10,8081000.0,None,None,None,14TH ST,None,None,None,None,None,None,None,38.0,None,LANDERS ST,15TH ST,None,POINT (-122.427832530979 37.767321079125)
11,9522000.0,None,None,None,GRIFFITH ST,None,None,None,None,None,None,None,45.0,None,NAVY RD,NAVY RD END,None,POINT (-122.379759196345 37.729615108064)
12,10040000.0,None,None,None,25TH ST,None,None,None,None,None,None,None,47.0,None,OSAGE ALY,26TH ST,None,POINT (-122.418788452017 37.749700495352)
13,8315000.0,None,None,None,LOWER TERR,None,None,None,None,None,None,None,40.0,None,LEVANT ST,STATES ST,None,POINT (-122.442307215889 37.764470082103)
14,5382000.0,None,None,None,22ND ST,None,None,None,None,None,None,None,26.0,None,FAIR OAKS ST,23RD ST,None,POINT (-122.424186408242 37.753893858191)
15,11807000.0,None,None,None,BRIGHT ST,None,None,None,None,None,None,None,51.0,None,SHIELDS ST,SHIELDS ST END,None,POINT (-122.463145662389 37.71793770802)
16,5383000.0,None,None,None,23RD ST,None,None,None,None,None,None,None,27.0,None,FAIR OAKS ST,24TH ST,None,POINT (-122.424131347416 37.753313124466)
17,4667201.0,None,None,None,CASHMERE ST,None,None,None,None,None,None,None,18.0,None,DEDMAN CT,DEDMAN CT END,None,POINT (-122.384984179033 37.736905819135)
18,3760201.0,None,None,None,HUDSON AVE,None,None,None,None,None,None,None,10.0,None,CASHMERE ST,CASHMERE ST END,None,POINT (-122.382964551029 37.73586309558)
19,4700000.0,None,None,None,HARKNESS AVE,None,None,None,None,None,None,None,20.0,None,DELTA ST,HAMILTON ST,None,POINT (-122.40683524447 37.718858390944)
20,4996101.0,None,None,None,CASHMERE ST,None,None,None,None,None,None,None,21.0,None,DUKES CT,DUKES CT END,None,POINT (-122.386713884972 37.736903626076)
21,3914000.0,None,None,None,AGUA WY,None,None,None,None,None,None,None,12.0,None,CHAVES AVE,DEL SUR AVE,None,POINT (-122.453868902204 37.742027806022)
22,5221000.0,None,None,None,CORTLAND AVE,None,None,None,None,None,None,None,24.0,None,ELSIE ST,HLLY PARK CIR,None,POINT (-122.419965009683 37.739105181757)
23,7007000.0,None,None,None,APPLETON AVE,None,None,None,None,None,None,None,33.0,None,HOLLY PARK CIR,ELSIE ST,None,POINT (-122.420815692148 37.737762092432)
24,6036000.0,None,None,None,TERESITA BLVD,None,None,None,None,None,None,None,29.0,None,GAVIOTA WY,BELLA VISTA WY,None,POINT (-122.447844550848 37.739323120649)
25,275000.0,None,None,None,LAKE ST,None,None,None,None,None,None,None,1.0,None,5TH AVE,5TH ST END,None,POINT (-122.463660876709 37.787137796484)
26,7006000.0,None,None,None,APPLETON AVE,None,None,None,None,None,None,None,34.0,None,HOLLY PARK CIR,HIGHLAND AVE,None,POINT (-122.421031728246 37.737459797697)
27,4252000.0,None,None,None,POWERS AVE,None,None,None,None,None,None,None,14.0,None,COLERIDGE ST,COSO AVE,None,POINT (-122.418246989648 37.745977683268)
28,7019000.0,None,None,None,24TH ST,None,None,None,None,None,None,None,35.0,None,HOMESTEAD,25TH ST,None,POINT (-122.439464261255 37.749988749953)
29,4667101.0,None,None,None,CASHMERE ST,None,None,None,None,None,None,None,17.0,None,DEDMAN CT,DEDMAN CT END,None,POINT (-122.384673072915 37.736987706875)
30,2697000.0,None,None,None,OAKDALE AVE,None,None,None,None,None,None,None,6.0,None,BALDWIN CT,BALDWIN CT END,None,POINT (-122.380782030457 37.729680637515)
31,9037000.0,None,None,None,ORIZABA AVE,None,None,None,None,None,None,None,42.0,None,MINERVA ST,CAPITOL AVE,None,POINT (-122.461945537306 37.715745120587)
32,4253000.0,None,None,None,FAIR AVE,None,None,None,None,None,None,None,15.0,None,COLERIDGE ST,POWERS AVE,None,POINT (-122.418589118088 37.745474367703)
33,13007000.0,None,None,None,MANOR DR,None,None,None,None,None,None,None,52.0,None,UPLAND DR,NORTHGATE DR,None,POINT (-122.463175481249 37.728980084273)
34,5188000.0,None,None,None,PIERCE ST,None,None,None,None,None,None,None,23.0,None,ELLIS ST,STEINER ST,None,POINT (-122.435362590485 37.782004466882)
35,2531000.0,None,None,None,MADISON ST,None,None,None,None,None,None,None,5.0,None,ATHENS ST,PERU AVE,None,POINT (-122.424761940476 37.726562930306)
36,9037000.0,None,None,None,ORIZABA AVE,None,None,None,None,None,None,None,44.0,None,MINERVA ST,CAPITOL AVE,None,POINT (-122.459569928541 37.715759785158)
37,4552000.0,None,None,None,ROLPH ST,None,None,None,None,None,None,None,16.0,None,CURTIS ST,MORSE ST,None,POINT (-122.440155057117 37.714693812439)
38,11669000.0,None,None,None,VELASCO AVE,None,None,None,None,None,None,None,50.0,None,SAWYER S,SUNRISE WY,None,POINT (-122.41602411209 37.709570069162)
39,4259000.0,None,None,None,KINGSTON ST,None,None,None,None,None,None,None,13.0,None,COLERIDGE ST,EUGENIA AVE,None,POINT (-122.421150072581 37.741514018797)
40,10040000.0,None,None,None,25TH ST,None,None,None,None,None,None,None,46.0,None,OSAGE ALY,26TH ST,None,POINT (-122.418826554789 37.750102742448)
41,8321000.0,None,None,None,GUERRERO ST,None,None,None,None,None,None,None,41.0,None,LIBERTY ST,VALENCIA ST,None,POINT (-122.422809388422 37.757609524036)
42,349000.0,None,None,None,LAKE ST,None,None,None,None,None,None,None,2.0,None,7TH AVE,7TH AVE END,None,POINT (-122.465802633876 37.787033978315)
43,4996201.0,None,None,None,CASHMERE ST,None,None,None,None,None,None,None,22.0,None,DUKES CT,DUKES CT END,None,POINT (-122.386565647799 37.736926307433)
44,8081000.0,None,None,None,14TH ST,None,None,None,None,None,None,None,39.0,None,LANDERS ST,15TH ST,None,POINT (-122.427771784269 37.766687366455)
45,1071000.0,None,None,None,LAKE ST,None,None,None,None,None,None,None,3.0,None,21ST AVE,21ST AVE END,None,POINT (-122.480903174098 37.78635017233)
46,7003000.0,None,None,None,MURRAY ST,None,None,None,None,None,None,None,31.0,None,HOLLY PARK CIR,PARK ST,None,POINT (-122.419977063718 37.736176059736)
47,7838000.0,None,None,None,MISSION ST,None,None,None,None,None,None,None,36.0,None,KINGSTON ST,SAN JOSE AVE,None,POINT (-122.422898847059 37.741728574768)
48,6036000.0,None,None,None,TERESITA BLVD,None,None,None,None,None,None,None,30.0,None,GAVIOTA WY,BELLA VISTA WY,None,POINT (-122.447944790213 37.738706950034)
49,3007000.0,None,None,None,HOLLY PARK CIRCLE,None,None,None,None,None,None,None,9.0,None,BOCANA ST,ELLERT ST,None,POINT (-122.419172712096 37.738408861396)
50,1113000.0,None,None,None,GUERRERO ST,None,None,None,None,None,None,None,4.0,None,21ST ST,VALENCIA ST,None,POINT (-122.422649097733 37.756815550644)
51,9037000.0,None,None,None,ORIZABA AVE,None,None,None,None,None,None,None,43.0,None,MINERVA ST,CAPITOL AVE,None,POINT (-122.460759148472 37.715752449717)

In [75]:
stops = pd.read_csv(
    '/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/evictionmodel_190final/data/geocoded_muni_stops_bytract.csv', 
    header=None, 
    names=['Tract', 'Number Stops'])

stops = stops[stops["Tract"] != 'Nan']
stops["Tract"] = stops["Tract"].astype(int)
stops.head()

        Tract  Number Stops
0  6041131100            27
1  6075010100            32
2  6075010200            32
3  6075010300            13
4  6075010400            24

In [76]:
features = pd.read_csv("data/features_with_neighbor_means.csv")
features.head()

,Unnamed: 0,Unnamed: 0.1,Geoid,num Evictions,geoid_year,Total Population,Total Housing Units,Total; Estimate; Average household size,Year,Median Year Structure Built,Median Year Moved In,Percent with Bachelor's degree,Median rent burden,Evictions per units,Percent Black,Percent White,Percent Asian,Percent Native,"Percent H, PI",Neighbors Mean
0,0,0,6075010100,2,60750101002011,3851.0000,2278.0000,1.750000,2011,1971.000000,2005.000000,34.00000,28.40000,0.000878,0.089847,0.437808,0.391327,0.002856,0.000000,0.0
1,1,1,6075010200,1,60750102002012,4040.0000,2946.0000,1.510000,2012,1939.000000,2005.000000,42.10000,22.50000,0.000339,0.011139,0.824257,0.087624,0.000000,0.000000,0.0
2,2,2,6075010200,1,60750102002017,4668.5488,2044.1584,2.504992,2017,1944.264423,2006.528939,508.85824,28.24032,0.001267,0.043886,0.514993,0.335039,0.003474,0.003172,0.0
3,3,3,6075010300,2,60750103002012,4393.0000,2254.0000,2.260000,2012,1939.000000,2005.000000,31.10000,24.30000,0.000887,0.000000,0.648532,0.351468,0.000000,0.000000,0.0
4,4,4,6075010300,2,60750103002013,4729.0000,2303.0000,2.290000,2013,1939.000000,2007.000000,31.30000,26.10000,0.000868,0.000000,0.577289,0.401988,0.000000,0.000000,2.0

In [84]:
features_withstops = pd.merge(features, stops, how='left', left_on="Geoid", right_on="Tract")
len(features_withstops)
features_withstops.to_csv("data/features_with_stops.csv")

In [80]:
shuttles = pd.read_csv("data/shuttles_geocodedbytract.csv")
shuttles.head()

,Unnamed: 0,from_st,to_st,geometry,Latitude,Longitude
0,0,16TH ST,17TH ST,POINT (-122.431645756432 37.763622580921),37.763623,-122.431646
1,1,HUDSON AVE,CASHMERE ST END,POINT (-122.382957235907 37.735744935444),37.735745,-122.382957
2,2,HUDSON AVE,HARBOR RD,POINT (-122.381188030573 37.733369713131),37.733370,-122.381188
3,3,HUDSON AVE,REUEL CT END,POINT (-122.383074321058 37.736501775361),37.736502,-122.383074
4,4,PARK ST,HIGHLAND AVE,POINT (-122.418862411824 37.737045357212),37.737045,-122.418862