In [296]:
import pandas as pd
import geopandas as gp
import numpy as np
import censusgeocode as cg
import time
import os

In [244]:
census_tracts = gp.read_file('/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/evictionmodel_190final/cb_2017_06_tract_500k/cb_2017_06_tract_500k.shp')
sf_tracts = census_tracts[census_tracts['COUNTYFP'] == '075']
sf_tracts.head() #196 census tracts in SF

,STATEFP,COUNTYFP,TRACTCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
430,06,075,010200,1400000US06075010200,06075010200,102,CT,515959,295388,"POLYGON ((-122.426671 37.809639, -122.424876 3..."
431,06,075,011200,1400000US06075011200,06075011200,112,CT,177415,0,"POLYGON ((-122.416292 37.793892, -122.415218 3..."
432,06,075,012401,1400000US06075012401,06075012401,124.01,CT,91972,0,"POLYGON ((-122.417707 37.784236, -122.416072 3..."
433,06,075,013300,1400000US06075013300,06075013300,133,CT,581310,0,"POLYGON ((-122.459476 37.789711, -122.45274 37..."
434,06,075,015900,1400000US06075015900,06075015900,159,CT,296386,0,"POLYGON ((-122.434562 37.784152, -122.431291 3..."

In [245]:
sf_evictions = pd.read_csv("/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/evictionmodel_190final/data/Eviction_Notices.csv")
sf_evictions["Year"] = sf_evictions["File Date"].astype(str).apply(lambda row: row[6:])
sf_evictions["Year"] = sf_evictions["Year"].astype(int)
sf_evictions_11 = sf_evictions[sf_evictions["Year"] >= 2011].dropna()
sf_evictions_11.head()

/Users/ameliabaum/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Eviction ID,Address,City,State,Eviction Notice Source Zipcode,File Date,Non Payment,Breach,Nuisance,Illegal Use,...,Other Cause,Late Payments,Lead Remediation,Development,Good Samaritan Ends,Constraints Date,Supervisor District,Neighborhoods - Analysis Boundaries,Location,Year
6,M172623,100 Block Of Charles Street,San Francisco,CA,94131,10/19/2017,False,False,False,False,...,False,False,False,False,False,12/17/2022,8.0,Glen Park,"(37.738336951880164, -122.4256608010048)",2017
10,M172628,1300 Block Of Chestnut Street,San Francisco,CA,94123,10/23/2017,False,False,False,False,...,False,False,False,False,False,12/17/2022,2.0,Marina,"(37.80223066530217, -122.42556524759928)",2017
14,M172503,1200 Block Of 41st Avenue,San Francisco,CA,94122,10/02/2017,False,False,False,False,...,False,False,False,False,False,11/29/2022,4.0,Sunset/Parkside,"(37.76346716977734, -122.50069529991866)",2017
22,M172511,0 Block Of 5th Avenue,San Francisco,CA,94118,10/10/2017,False,False,False,False,...,False,False,False,False,False,12/05/2022,2.0,Inner Richmond,"(37.787705866671075, -122.46361972068956)",2017
25,M172709,100 Block Of Prospect Avenue,San Francisco,CA,94110,10/26/2017,False,False,False,False,...,False,False,False,False,False,12/24/2022,9.0,Bernal Heights,"(37.74296049255459, -122.41894065545237)",2017

In [246]:
#split the lat and lon into different columns
sf_evictions_11["Latitude"] = sf_evictions_11["Location"].astype(str).apply(lambda row: row.split(",")[0][1:])
sf_evictions_11["Longitude"] = sf_evictions_11["Location"].astype(str).apply(lambda row: row.split(",")[1][:-1])

sf_evictions_11

,Eviction ID,Address,City,State,Eviction Notice Source Zipcode,File Date,Non Payment,Breach,Nuisance,Illegal Use,...,Lead Remediation,Development,Good Samaritan Ends,Constraints Date,Supervisor District,Neighborhoods - Analysis Boundaries,Location,Year,Latitude,Longitude
6,M172623,100 Block Of Charles Street,San Francisco,CA,94131,10/19/2017,False,False,False,False,...,False,False,False,12/17/2022,8.0,Glen Park,"(37.738336951880164, -122.4256608010048)",2017,37.738336951880164,-122.4256608010048
10,M172628,1300 Block Of Chestnut Street,San Francisco,CA,94123,10/23/2017,False,False,False,False,...,False,False,False,12/17/2022,2.0,Marina,"(37.80223066530217, -122.42556524759928)",2017,37.80223066530217,-122.42556524759928
14,M172503,1200 Block Of 41st Avenue,San Francisco,CA,94122,10/02/2017,False,False,False,False,...,False,False,False,11/29/2022,4.0,Sunset/Parkside,"(37.76346716977734, -122.50069529991866)",2017,37.76346716977734,-122.50069529991866
22,M172511,0 Block Of 5th Avenue,San Francisco,CA,94118,10/10/2017,False,False,False,False,...,False,False,False,12/05/2022,2.0,Inner Richmond,"(37.787705866671075, -122.46361972068956)",2017,37.787705866671075,-122.46361972068956
25,M172709,100 Block Of Prospect Avenue,San Francisco,CA,94110,10/26/2017,False,False,False,False,...,False,False,False,12/24/2022,9.0,Bernal Heights,"(37.74296049255459, -122.41894065545237)",2017,37.74296049255459,-122.41894065545237
30,M172508,400 Block Of Staples Avenue,San Francisco,CA,94112,10/04/2017,False,False,False,False,...,False,False,False,01/01/2023,7.0,West of Twin Peaks,"(37.72900535140412, -122.45178538729365)",2017,37.72900535140412,-122.45178538729365
32,M172625,100 Block Of Cordova Street,San Francisco,CA,94112,10/23/2017,False,False,False,False,...,False,False,False,12/12/2022,11.0,Excelsior,"(37.71193832413155, -122.43563244891334)",2017,37.71193832413155,-122.43563244891334
39,M172507,5500 Block Of California Street,San Francisco,CA,94121,10/04/2017,False,False,False,False,...,False,False,False,11/28/2022,1.0,Outer Richmond,"(37.784191971543926, -122.47696912767651)",2017,37.784191971543926,-122.47696912767651
43,M172501,1500 Block Of Fulton Street,San Francisco,CA,94117,10/02/2017,False,False,False,False,...,False,False,False,11/29/2022,5.0,Lone Mountain/USF,"(37.776276302674454, -122.44229944730586)",2017,37.776276302674454,-122.44229944730586
44,M172627,2500 Block Of Quintara Street,San Francisco,CA,94116,10/23/2017,False,False,False,False,...,False,False,False,12/18/2022,4.0,Sunset/Parkside,"(37.747857144692475, -122.49268820953169)",2017,37.747857144692475,-122.49268820953169
46,M172707,0 Block Of Red Rock Way,San Francisco,CA,94131,10/24/2017,False,False,False,False,...,False,False,False,12/19/2022,8.0,Noe Valley,"(37.746036675352386, -122.4421966322588)",2017,37.746036675352386,-122.4421966322588
51,M172514,4800 Block Of 17th Street,San Francisco,CA,94117,10/12/2017,False,False,False,False,...,False,False,False,12/04/2022,5.0,Inner Sunset,"(37.76154986295495, -122.449844913005)",2017,37.76154986295495,-122.449844913005
66,M172626,0 Block Of Carmel Street,San Francisco,CA,94117,10/23/2017,False,False,False,False,...,False,False,False,12/19/2022,5.0,Inner Sunset,"(37.76091494605406, -122.44702383140725)",2017,37.76091494605406,-122.44702383140725
77,M172510,4000 Block Of Mission Street,San Francisco,CA,94112,10/10/2017,False,False,False,False,...,False,False,False,12/05/2022,9.0,Bernal Heights,"(37.732174584976555, -122.42779351441527)",2017,37.732174584976555,-122.42779351441527
83,M172620,4900 Block Of Mission Street,San Francisco,CA,94112,10/16/2017,False,False,False,False,...,False,False,False,12/12/2022,11.0,Excelsior,"(37.718846108529924, -122.43909283745074)",2017,37.718846108529924,-122.43909283745074
90,M172502,2200 Block Of Francisco Street,San Francisco,CA,94123,10/02/2017,False,False,False,False,...,False,False,False,11/26/2022,2.0,Marina,"(37.80096275768972, -122.44219021259764)",2017,37.80096275768972,-122.44219021259764
94,M172621,0 Block Of Joost Avenue,San Francisco,CA,94131,10/17/2017,False,False,False,False,...,False,False,False,12/11/2022,8.0,West of Twin Peaks,"(37.73243482554961, -122.4368505501365)",2017,37.73243482554961,-122.4368505501365
95,M172500,1600 Block Of Alabama Street,San Francisco,CA,94110,10/02/2017,False,False,False,False,...,False,False,False,11/27/2022,9.0,Bernal Heights,"(37.74594338615151, -122.41060051934308)",2017,37.74594338615151,-122.41060051934308
96,M172509,700 Block Of 42nd Avenue,San Francisco,CA,94121,10/10/2017,False,False,False,False,...,False,False,False,11/29/2022,1.0,Outer Richmond,"(37.77453388106368, -122.5026721762603)",2017,37.77453388106368,-122.5026721762603
97,M172505,600 Block Of Burnett Avenue,San Francisco,CA,94131,10/04/2017,False,False,False,False,...,False,False,False,11/27/2022,8.0,Twin Peaks,"(37.75133055251515, -122.44446883018355)",2017,37.75133055251515,-122.44446883018355
101,M172624,2200 Block Of 47th Avenue,San Francisco,CA,94116,10/20/2017,False,False,False,False,...,False,False,False,01/15/2023,4.0,Sunset/Parkside,"(37.74452300324143, -122.50596004398315)",2017,37.74452300324143,-122.50596004398315
103,M172512,1600 Block Of Quesada Avenue,San Francisco,CA,94124,10/11/2017,False,False,False,False,...,False,False,False,01/08/2023,10.0,Bayview Hunters Point,"(37.73271193211899, -122.39046276096872)",2017,37.73271193211899,-122.39046276096872
105,M172513,0 Block Of Cayuga Avenue,San Francisco,CA,94112,10/11/2017,False,False,False,False,...,False,False,False,12/09/2022,8.0,Outer Mission,"(37.73129547036364, -122.43014966127174)",2017,37.73129547036364,-122.43014966127174
108,M172499,600 Block Of Andover Street,San Francisco,CA,94110,09/29/2017,False,False,False,False,...,False,False,False,11/27/2022,9.0,Bernal Heights,"(37.735250365758155, -122.4168605417695)",2017,37.735250365758155,-122.4168605417695
118,M172713,800 Block Of Capp Street,San Francisco,CA,94110,11/01/2017,False,False,False,False,...,False,False,False,12/18/2022,9.0,Mission,"(37.75309998106267, -122.41750085090202)",2017,37.75309998106267,-122.41750085090202
127,M172899,500 Block Of Naples Street,San Francisco,CA,94112,11/14/2017,False,False,False,False,...,False,False,False,01/08/2023,11.0,Excelsior,"(37.720048773557465, -122.4317358731155)",2017,37.720048773557465,-122.4317358731155
130,M172901,1600 Block Of 29th Avenue,San Francisco,CA,94122,11/21/2017,False,False,False,False,...,False,False,False,01/12/2023,4.0,Sunset/Parkside,"(37.756562003494416, -122.48745155430078)",2017,37.756562003494416,-122.48745155430078
143,M172716,200 Block Of 4th Avenue,San Francisco,CA,94118,11/02/2017,False,False,False,False,...,False,False,False,12/30/2022,1.0,Inner Richmond,"(37.783975803643855, -122.46227844344496)",2017,37.783975803643855,-122.46227844344496
175,M172710,200 Block Of Silliman Street,San Francisco,CA,94134,10/30/2017,False,False,False,False,...,False,False,False,12/26/2022,9.0,Portola,"(37.73064132380639, -122.4075866521839)",2017,37.73064132380639,-122.4075866521839
182,M172900,0 Block Of Melra Court,San Francisco,CA,94134,11/14/2017,False,False,False,False,...,False,False,False,01/06/2023,10.0,Visitacion Valley,"(37.709838464296354, -122.41056021201132)",2017,37.709838464296354,-122.41056021201132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39246,M161067,700 Block Of Geneva Avenue,San Francisco,CA,94112,03/30/2016,False,False,False,False,...,False,False,False,05/28/2021,11.0,Outer Mission,"(37.718538917451774, -122.44337602882476)",2016,37.718538917451774,-122.44337602882476
39260,M150854,3600 Block Of Mission Street,San Francisco,CA,94110,04/17/2015,False,False,False,False,...,False,False,False,04/07/2018,9.0,Bernal Heights,"(37.738121997112685, -122.42392539123186)",2015,37.738121997112685,-122.42392539123186
39330,M141785,2300 Block Of 27th Avenue,San Francisco,CA,94116,09/11/2014,False,False,False,False,...,False,False,False,09/08/2017,4.0,Sunset/Parkside,"(37.74360345044117, -122.48439829043349)",2014,37.74360345044117,-122.48439829043349
39333,M160814,500 Block Of 22nd Avenue,San Francisco,CA,94121,03/01/2016,False,False,False,False,...,False,False,False,04/29/2021,1.0,Outer Richmond,"(37.77738322770273, -122.48124465192733)",2016,37.77738322770273,-122.48124465192733
39334,M132047,2400 Block Of 35th Avenue,San Francisco,CA,94116,12/06/2013,False,False,False,False,...,False,False,False,12/05/2016,4.0,Sunset/Parkside,"(37.74135846644042, -122.49284057047088)",2013,37.74135846644042,-122.49284057047088
39335,M120377,500 Block Of 42nd Avenue,San Francisco,CA,94121,05/07/2012,False,False,False,False,...,False,False,False,05/02/2015,1.0,Outer Richmond,"(37.77829990457353, -122.50280751593341)",2012,37.77829990457353,-122.50280751593341
39403,M130294,500 Block Of Bowdoin Street,San Francisco,CA,94134,03/28/2013,False,False,False,False,...,False,False,False,03/27/2016,9.0,Portola,"(37.728812924604405, -122.41181802867497)",2013,37.728812924604405,-122.41181802867497
39424,M130306,0 Block Of Montezuma Street,San Francisco,CA,94110,04/08/2013,False,False,False,False,...,False,False,False,04/08/2016,9.0,Bernal Heights,"(37.745908110573325, -122.41632314566068)",2013,37.745908110573325,-122.41632314566068
39443,M161071,200 Block Of Moultrie Street,San Francisco,CA,94110,04/04/2016,False,False,False,False,...,False,False,False,04/26/2021,9.0,Bernal Heights,"(37.741011351822074, -122.41580918702604)",2016,37.741011351822074,-122.41580918702604
39464,M140747,1300 Block Of 28th Avenue,San Francisco,CA,94122,04/16/2014,False,False,False,False,...,False,False,False,04/15/2017,4.0,Sunset/Parkside,"(37.762203195588214, -122.486774240263)",2014,37.762203195588214,-122.486774240263
39476,M170984,300 Block Of Foote Avenue,San Francisco,CA,94112,04/14/2017,False,False,False,False,...,False,False,False,06/04/2022,11.0,Outer Mission,"(37.71554239381501, -122.44848015196821)",2017,37.71554239381501,-122.44848015196821
39495,M142298,3900 Block Of 26th Street,San Francisco,CA,94131,10/17/2014,False,False,False,False,...,False,False,False,08/15/2017,8.0,Noe Valley,"(37.748483821873776, -122.42823984811396)",2014,37.748483821873776,-122.42823984811396
39513,M120770,2700 Block Of Greenwich Street,San Francisco,CA,94123,07/19/2012,False,False,False,False,...,False,False,False,07/16/2015,2.0,Marina,"(37.797740333660855, -122.44495092153564)",2012,37.797740333660855,-122.44495092153564
39533,M151091,3700 Block Of 26th Street,San Francisco,CA,94110,05/06/2015,False,False,False,False,...,False,False,False,05/04/2018,8.0,Mission,"(37.74862337943253, -122.42425719869715)",2015,37.74862337943253,-122.42425719869715
39548,M120774,1100 Block Of Valencia Street,San Francisco,CA,94110,07/30/2012,False,False,False,False,...,False,False,False,07/27/2015,9.0,Mission,"(37.75450309002492, -122.42081913269303)",2012,37.75450309002492,-122.42081913269303
39580,M152454,600 Block Of Silliman Street,San Francisco,CA,94134,09/11/2015,False,False,False,False,...,False,False,False,09/02/2018,9.0,Portola,"(37.72950677078533, -122.41148568670643)",2015,37.72950677078533,-122.41148568670643
39624,M151521,900 Block Of Valencia Street,San Francisco,CA,94110,06/16/2015,False,False,False,False,...,False,False,False,06/15/2018,9.0,Mission,"(37.75730586479415, -122.42108671824279)",2015,37.75730586479415,-122.42108671824279
39626,M110024,2000 Block Of Pine Street,San Francisco,CA,94115,02/15/2011,False,False,False,False,...,False,False,False,02/14/2014,5.0,Pacific Heights,"(37.78841845547915, -122.42952307995114)",2011,37.78841845547915,-122.42952307995114
39628,M153430,100 Block Of Naples Street,San Francisco,CA,94112,12/17/2015,False,False,False,False,...,False,False,False,02/12/2021,11.0,Excelsior,"(37.72632644696793, -122.42715321680285)",2015,37.72632644696793,-122.42715321680285
39640,M131679,500 Block Of Diamond Street,San Francisco,CA,94114,09/11/2013,False,False,False,False,...,False,False,False,09/10/2016,8.0,Noe Valley,"(37.75395303997945, -122.4364941637476)",2013,37.75395303997945,-122.4364941637476
39650,M120023,600 Block Of Guerrero Street,San Francisco,CA,94110,01/09/2012,False,False,False,False,...,False,False,False,01/03/2015,8.0,Mission,"(37.76077326249153, -122.4236036773369)",2012,37.76077326249153,-122.4236036773369
39653,M170513,600 Block Of Rhode Island Street,San Francisco,CA,94107,03/01/2017,False,False,False,False,...,False,False,False,04/29/2022,10.0,Potrero Hill,"(37.76158578759801, -122.40233404826925)",2017,37.76158578759801,-122.40233404826925
39711,M163713,400 Block Of Flood Avenue,San Francisco,CA,94112,12/02/2016,False,False,False,False,...,False,False,False,01/27/2022,7.0,West of Twin Peaks,"(37.729932179744985, -122.44999549925754)",2016,37.729932179744985,-122.44999549925754
39752,M150364,800 Block Of Brazil Avenue,San Francisco,CA,94112,03/06/2015,False,False,False,False,...,False,False,False,02/28/2018,11.0,Excelsior,"(37.72149318990423, -122.42800269213774)",2015,37.72149318990423,-122.42800269213774
39771,M171912,300 Block Of Franklin Street,San Francisco,CA,94102,07/31/2017,False,False,False,False,...,False,False,False,09/25/2022,5.0,Hayes Valley,"(37.777316514399764, -122.42144658866007)",2017,37.777316514399764,-122.42144658866007
39775,M152875,0 Block Of Lunado Way,San Francisco,CA,94127,10/13/2015,False,False,False,False,...,False,False,False,12/05/2020,7.0,West of Twin Peaks,"(37.72266777035688, -122.47130250945453)",2015,37.72266777035688,-122.47130250945453
39782,M152600,600 Block Of Santiago Street,San Francisco,CA,94116,09/25/2015,False,False,False,False,...,False,False,False,11/19/2020,7.0,West of Twin Peaks,"(37.74493295449598, -122.47421522324102)",2015,37.74493295449598,-122.47421522324102
39821,M110246,0 Block Of Howth Street,San Francisco,CA,94112,06/03/2011,False,False,False,False,...,False,False,False,05/28/2014,7.0,Oceanview/Merced/Ingleside,"(37.722546856184486, -122.44990012562252)",2011,37.722546856184486,-122.44990012562252
39841,M130627,500 Block Of 19th Avenue,San Francisco,CA,94121,05/06/2013,False,False,False,False,...,False,False,False,05/03/2016,1.0,Outer Richmond,"(37.77752921386303, -122.4780306278944)",2013,37.77752921386303,-122.4780306278944
39845,M151096,1000 Block Of Girard Street,San Francisco,CA,94134,05/11/2015,False,False,False,False,...,False,False,False,05/06/2018,10.0,Portola,"(37.71959982902303, -122.40128531007775)",2015,37.71959982902303,-122.40128531007775

In [247]:
def getTract(lon, lat):
#pings the FCC API to geocode lat lon coordinates to other geograpies. Returns a 2 item array of [geoid, tract name]
    try:
        result = cg.coordinates(lon, lat)
        tract = result['Census Tracts'][0]['NAME'] #alt use 'TRACT' for partial fips
        return tract
    except(ValueError, TypeError):
        return 'Nan'

In [248]:
def getGeoid(lon, lat):
#pings the FCC API to geocode lat lon coordinates to other geograpies. Returns a 2 item array of [geoid, tract name]
    try:
        result = cg.coordinates(lon, lat)
        geoid = result['Census Tracts'][0]['GEOID']
        return geoid
    except(ValueError, TypeError):
        return 'Nan'

In [249]:
start = time.time()
sf_evictions_11["Geoid"] = sf_evictions_11.apply(lambda row: getGeoid(row["Longitude"], row["Latitude"]), axis=1)
end = time.time()
elapsed = end-start #this takes like ~30 mins

In [394]:
sf_evictions_11 = sf_evictions_11.replace({False: 0, True: 1})

In [395]:
sf_evictions_11.to_csv("data/evictions_geocided_11.csv")

In [406]:
evictions_geocoded11_tractandyear = sf_evictions_11.groupby(["Geoid", 
        "Year"])
evictions_geocoded11_tractandyear
# .drop(["Neighborhoods - Analysis Boundaries", "Location", "Latitude", "Longitude", 
#         "Eviction Notice Source Zipcode", "Address", "City", "State", "Constraints Date", "File Date", "Supervisor District"], axis=1) #166 census tracts represented

In [422]:
for year, df in evictions_geocoded11_tractandyear:   
#     total = df[['Non Payment', 'Breach',
#        'Nuisance', 'Illegal Use', 'Failure to Sign Renewal', 'Access Denial',
#        'Unapproved Subtenant', 'Owner Move In', 'Demolition',
#        'Capital Improvement', 'Substantial Rehab', 'Ellis Act WithDrawal',
#        'Condo Conversion', 'Roommate Same Unit', 'Other Cause',
#        'Late Payments', 'Lead Remediation', 'Development',
#        'Good Samaritan Ends']].sum(axis=1)
    total = len(df) # i think this should work as the number of records, which translates to the number of evictions
    df["Total"] = total
   
    #print(df) #this is the part of the evictions dataframe that corresponds to a given year
#     merged = df.merge(units_feature[str(year-2)], how='left', left_on='Geoid', right_on='Id2')
# merged

/Users/ameliabaum/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [428]:
evictions_geocoded11_tractandyear.columns

AttributeError: Cannot access attribute 'columns' of 'DataFrameGroupBy' objects, try using the 'apply' method

In [ ]:
evictions_geocoded11_tractandyear.to_csv("data/evictions_geocoded11_tractandyear.csv")

In [295]:
evictions_geocoded11_tractandyear = pd.read_csv("data/evictions_geocoded11_tractandyear.csv")
evictions_geocoded11_tractandyear["Tract"] = evictions_geocoded11_tractandyear["Geoid"].astype(str).apply(lambda row: row[5:])
evictions_geocoded11_tractandyear["tract_year"] = evictions_geocoded11_tractandyear["Tract"] + evictions_geocoded11_tractandyear["Year"].astype(str)
evictions_geocoded11_tractandyear.to_csv("data/evictions_geocoded11_tractandyear.csv")

In [358]:
data_path = '/Users/ameliabaum/Desktop/Amelia/Berkeley 2018-2019/EnRes C190/evictionmodel_190final/data/'
#table B02001 race
race_feature = {}
for race_file in os.listdir(data_path+'B02001_race'):
    year = race_file.split("_")[1]
    race_feature['20'+year] = pd.read_csv(data_path+'B02001_race/'+race_file)
print(race_feature.keys())


#table B25071 rent burden
burden_feature = {}
for burden_file in os.listdir(data_path+'B25071_burden'):
    year = burden_file.split("_")[1]
    if year in ['09', '10', '11', '12', '13', '14', '15', '16']:
        burden_feature['20'+year] = pd.read_csv(data_path+'B25071_burden/'+burden_file)
print(burden_feature.keys())

#table S1101 household size
hsize_feature = {}
for size_file in os.listdir(data_path+'S1101_size'):
    year = size_file.split("_")[1]
    if year in ['09', '10', '11', '12', '13', '14', '15', '16']:
        hsize_feature['20'+year] = pd.read_csv(data_path+'S1101_size/'+size_file)
print(hsize_feature.keys())

#table S1501 % with bachelors degree
edu_feature = {}
for edu_file in os.listdir(data_path+'S1501_edu'):
    year = edu_file.split("_")[1]
    if year in ['09', '10', '11', '12', '13', '14', '15', '16']:
        edu_feature['20'+year] = pd.read_csv(data_path+'S1501_edu/'+edu_file)
print(edu_feature.keys())

#table B02001 race
race_feature = {}
for race_file in os.listdir(data_path+'B02001_race'):
    year = race_file.split("_")[1]
    if year in ['09', '10', '11', '12', '13', '14', '15', '16']:
        race_feature['20'+year] = pd.read_csv(data_path+'B02001_race/'+race_file)
print(race_feature.keys())



#table S1101 household size
size_feature = {}
for size_file in os.listdir(data_path+'S1101_size'):
    year = size_file.split("_")[1]
    if year in ['09', '10', '11', '12', '13', '14', '15', '16']:
        size_feature['20'+year] = pd.read_csv(data_path+'S1101_size/'+size_file)
print(size_feature.keys())

#table B25035 median year built
built_feature = {}
for built_file in os.listdir(data_path+'B25035_yearbuilt'):
    year = built_file.split("_")[1]
    if year in ['09', '10', '11', '12', '13', '14', '15', '16']:
        built_feature['20'+year] = pd.read_csv(data_path+'B25035_yearbuilt/'+built_file)
print(built_feature.keys())


#table B25039 median renter moved in
moved_feature = {}
for moved_file in os.listdir(data_path+'B25039_moved'):
    year = moved_file.split("_")[1]
    if year in ['09', '10', '11', '12', '13', '14', '15', '16']:
        moved_feature['20'+year] = pd.read_csv(data_path+'B25039_moved/'+moved_file)
print(moved_feature.keys())


#table B25001 housing units in tract
units_feature = {}
for units_file in os.listdir(data_path+'B25001_units'):
    year = units_file.split("_")[1]
    if year in ['09', '10', '11', '12', '13', '14', '15', '16']:
        foo = pd.read_csv(data_path+'B25001_units/'+units_file)
        print(foo.dtypes)
        units_feature['20'+year] = pd.read_csv(data_path+'B25001_units/'+units_file)
print(units_feature.keys())

dict_keys(['2015', '2012', '2010', '2011', '2016', '2013', '2009', '2014'])
dict_keys(['2009', '2015', '2010', '2011', '2014', '2012', '2013', '2016'])
dict_keys(['2013', '2009', '2012', '2016', '2014', '2010', '2011', '2015'])
dict_keys(['2016', '2012', '2011', '2009', '2015', '2013', '2014', '2010'])
dict_keys(['2015', '2012', '2010', '2011', '2016', '2013', '2009', '2014'])
dict_keys(['2013', '2009', '2012', '2016', '2014', '2010', '2011', '2015'])
dict_keys(['2010', '2016', '2011', '2014', '2013', '2009', '2012', '2015'])
dict_keys(['2009', '2013', '2014', '2015', '2012', '2010', '2011', '2016'])
Id2                 int64
Geography          object
Estimate; Total     int64
dtype: object
Id2                 int64
Geography          object
Estimate; Total     int64
dtype: object
Id2                 int64
Geography          object
Estimate; Total     int64
dtype: object
Id2                 int64
Geography          object
Estimate; Total     int64
dtype: object
Id2                 int64
Geography          object
Estimate; Total     int64
dtype: object
Id2                 int64
Geography          object
Estimate; Total     int64
dtype: object
Id2                 int64
Geography          object
Estimate; Total     int64
dtype: object
Id2                 int64
Geography          object
Estimate; Total     int64
dtype: object
dict_keys(['2015', '2012', '2013', '2009', '2014', '2011', '2016', '2010'])

In [386]:
#use groupby to group the evictions data by year, and then perform in inner merge with the feature
evictions = pd.read_csv("data/evictions_geocoded11_tractandyear.csv").drop("Unnamed: 0", axis=1)
total = evictions[['Non Payment', 'Breach', 'Nuisance',
       'Illegal Use', 'Failure to Sign Renewal', 'Access Denial',
       'Unapproved Subtenant', 'Owner Move In', 'Demolition',
       'Capital Improvement', 'Substantial Rehab', 'Ellis Act WithDrawal',
       'Condo Conversion', 'Roommate Same Unit', 'Other Cause',
       'Late Payments', 'Lead Remediation', 'Development',
       'Good Samaritan Ends']]
evictions["Total Evictions"] = total.sum(axis=1)
total_evictionsbytract = evictions[["Geoid", "Year", "Tract", "tract_year", "Total Evictions"]].dropna()
total_evictionsbytract["Geoid"] = total_evictionsbytract["Geoid"].astype(int)
evictions

,Geoid,Year,Eviction ID,Non Payment,Breach,Nuisance,Illegal Use,Failure to Sign Renewal,Access Denial,Unapproved Subtenant,...,Condo Conversion,Roommate Same Unit,Other Cause,Late Payments,Lead Remediation,Development,Good Samaritan Ends,Tract,tract_year,Total Evictions
0,6075010100,2011,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,10100.0,101002011,38
1,6075010200,2012,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10200.0,102002012,19
2,6075010200,2017,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10200.0,102002017,19
3,6075010300,2012,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,10300.0,103002012,38
4,6075010300,2013,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,10300.0,103002013,38
5,6075010300,2014,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,10300.0,103002014,57
6,6075010300,2015,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,10300.0,103002015,76
7,6075010300,2016,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10300.0,103002016,19
8,6075010300,2017,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10300.0,103002017,19
9,6075010300,2018,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,10300.0,103002018,38
10,6075010400,2011,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,10400.0,104002011,76
11,6075010400,2012,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,10400.0,104002012,57
12,6075010400,2013,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,10400.0,104002013,76
13,6075010400,2015,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,10400.0,104002015,76
14,6075010400,2016,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,10400.0,104002016,95
15,6075010400,2017,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,10400.0,104002017,38
16,6075010400,2018,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,10400.0,104002018,76
17,6075010600,2013,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10600.0,106002013,19
18,6075010600,2014,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10600.0,106002014,19
19,6075010600,2015,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,10600.0,106002015,57
20,6075010600,2016,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10600.0,106002016,19
21,6075010600,2017,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10600.0,106002017,19
22,6075010700,2012,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10700.0,107002012,19
23,6075010700,2015,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10700.0,107002015,19
24,6075010800,2011,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10800.0,108002011,19
25,6075010800,2012,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10800.0,108002012,19
26,6075010800,2013,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,10800.0,108002013,19
27,6075010800,2014,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,10800.0,108002014,57
28,6075010800,2015,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,10800.0,108002015,76
29,6075010800,2016,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,10800.0,108002016,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,6075047901,2014,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,47901.0,479012014,38
808,6075047901,2015,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,47901.0,479012015,76
809,6075047901,2016,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,47901.0,479012016,95
810,6075047901,2017,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,47901.0,479012017,133
811,6075047901,2018,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,47901.0,479012018,38
812,6075047902,2012,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,47902.0,479022012,19
813,6075047902,2013,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,47902.0,479022013,19
814,6075047902,2015,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,47902.0,479022015,19
815,6075047902,2016,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,47902.0,479022016,19
816,6075047902,2017,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,47902.0,479022017,19
817,6075060700,2011,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,60700.0,607002011,19
818,6075061000,2015,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,61000.0,610002015,19
819,6075061000,2016,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,61000.0,610002016,57
820,6075061100,2017,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,61100.0,611002017,19
821,6075061200,2011,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,61200.0,612002011,19
822,6075061200,2012,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,61200.0,612002012,38
823,6075061200,2015,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,61200.0,612002015,19
824,6075061400,2011,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,61400.0,614002011,19
825,6075061400,2012,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,61400.0,614002012,19
826,6075061400,2013,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,61400.0,614002013,57
827,6075061400,2014,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,61400.0,614002014,152
828,6075061400,2015,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,61400.0,614002015,57
829,6075061400,2016,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,61400.0,614002016,57
830,6075061500,2015,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,61500.0,615002015,19
831,6075061500,2016,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,61500.0,615002016,19
832,Nan,2012,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,NaN,2012,19
833,Nan,2013,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,NaN,2013,38
834,Nan,2014,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,NaN,2014,19
835,Nan,2015,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,NaN,2015,57
836,Nan,2018,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,NaN,2018,19

In [385]:
for year, df in total_evictionsbytract.groupby("Year"):
#     print(year)
#     print(year-2)
    #print(df) #this is the part of the evictions dataframe that corresponds to a given year
    merged = df.merge(units_feature[str(year-2)], how='left', left_on='Geoid', right_on='Id2')
merged

,Geoid,Year,Tract,tract_year,Total Evictions,Id2,Geography,Estimate; Total
0,6075010300,2018,10300.0,103002018,38,6075010300,"Census Tract 103, San Francisco County, Califo...",2378
1,6075010400,2018,10400.0,104002018,76,6075010400,"Census Tract 104, San Francisco County, Califo...",2844
2,6075010800,2018,10800.0,108002018,19,6075010800,"Census Tract 108, San Francisco County, Califo...",2743
3,6075011100,2018,11100.0,111002018,19,6075011100,"Census Tract 111, San Francisco County, Califo...",3337
4,6075011200,2018,11200.0,112002018,19,6075011200,"Census Tract 112, San Francisco County, Califo...",2339
5,6075012602,2018,12602.0,126022018,19,6075012602,"Census Tract 126.02, San Francisco County, Cal...",1830
6,6075012800,2018,12800.0,128002018,19,6075012800,"Census Tract 128, San Francisco County, Califo...",2635
7,6075012901,2018,12901.0,129012018,38,6075012901,"Census Tract 129.01, San Francisco County, Cal...",1688
8,6075012902,2018,12902.0,129022018,19,6075012902,"Census Tract 129.02, San Francisco County, Cal...",2264
9,6075013000,2018,13000.0,130002018,19,6075013000,"Census Tract 130, San Francisco County, Califo...",2646
10,6075013200,2018,13200.0,132002018,38,6075013200,"Census Tract 132, San Francisco County, Califo...",2650
11,6075015400,2018,15400.0,154002018,19,6075015400,"Census Tract 154, San Francisco County, Califo...",3166
12,6075015600,2018,15600.0,156002018,38,6075015600,"Census Tract 156, San Francisco County, Califo...",1575
13,6075015700,2018,15700.0,157002018,19,6075015700,"Census Tract 157, San Francisco County, Califo...",2831
14,6075015802,2018,15802.0,158022018,19,6075015802,"Census Tract 158.02, San Francisco County, Cal...",1684
15,6075016500,2018,16500.0,165002018,19,6075016500,"Census Tract 165, San Francisco County, Califo...",2527
16,6075016700,2018,16700.0,167002018,38,6075016700,"Census Tract 167, San Francisco County, Califo...",2538
17,6075017101,2018,17101.0,171012018,19,6075017101,"Census Tract 171.01, San Francisco County, Cal...",1970
18,6075017102,2018,17102.0,171022018,19,6075017102,"Census Tract 171.02, San Francisco County, Cal...",1829
19,6075017601,2018,17601.0,176012018,38,6075017601,"Census Tract 176.01, San Francisco County, Cal...",5530
20,6075020200,2018,20200.0,202002018,19,6075020200,"Census Tract 202, San Francisco County, Califo...",3425
21,6075020401,2018,20401.0,204012018,19,6075020401,"Census Tract 204.01, San Francisco County, Cal...",1831
22,6075020402,2018,20402.0,204022018,19,6075020402,"Census Tract 204.02, San Francisco County, Cal...",2731
23,6075020500,2018,20500.0,205002018,19,6075020500,"Census Tract 205, San Francisco County, Califo...",1447
24,6075020600,2018,20600.0,206002018,19,6075020600,"Census Tract 206, San Francisco County, Califo...",2923
25,6075020700,2018,20700.0,207002018,19,6075020700,"Census Tract 207, San Francisco County, Califo...",2951
26,6075020800,2018,20800.0,208002018,19,6075020800,"Census Tract 208, San Francisco County, Califo...",2879
27,6075020900,2018,20900.0,209002018,57,6075020900,"Census Tract 209, San Francisco County, Califo...",1963
28,6075021100,2018,21100.0,211002018,19,6075021100,"Census Tract 211, San Francisco County, Califo...",2113
29,6075021200,2018,21200.0,212002018,19,6075021200,"Census Tract 212, San Francisco County, Califo...",1563
...,...,...,...,...,...,...,...,...
64,6075030400,2018,30400.0,304002018,38,6075030400,"Census Tract 304, San Francisco County, Califo...",2052
65,6075030700,2018,30700.0,307002018,19,6075030700,"Census Tract 307, San Francisco County, Califo...",2810
66,6075031100,2018,31100.0,311002018,76,6075031100,"Census Tract 311, San Francisco County, Califo...",2667
67,6075031201,2018,31201.0,312012018,38,6075031201,"Census Tract 312.01, San Francisco County, Cal...",2066
68,6075031202,2018,31202.0,312022018,38,6075031202,"Census Tract 312.02, San Francisco County, Cal...",919
69,6075031400,2018,31400.0,314002018,19,6075031400,"Census Tract 314, San Francisco County, Califo...",1981
70,6075032601,2018,32601.0,326012018,38,6075032601,"Census Tract 326.01, San Francisco County, Cal...",1905
71,6075032602,2018,32602.0,326022018,38,6075032602,"Census Tract 326.02, San Francisco County, Cal...",1791
72,6075032700,2018,32700.0,327002018,19,6075032700,"Census Tract 327, San Francisco County, Califo...",2622
73,6075032801,2018,32801.0,328012018,38,6075032801,"Census Tract 328.01, San Francisco County, Cal...",1578
74,6075032802,2018,32802.0,328022018,19,6075032802,"Census Tract 328.02, San Francisco County, Cal...",1598
75,6075032902,2018,32902.0,329022018,38,6075032902,"Census Tract 329.02, San Francisco County, Cal...",1439
76,6075033000,2018,33000.0,330002018,19,6075033000,"Census Tract 330, San Francisco County, Califo...",2891
77,6075035100,2018,35100.0,351002018,76,6075035100,"Census Tract 351, San Francisco County, Califo...",2920
78,6075035201,2018,35201.0,352012018,57,6075035201,"Census Tract 352.01, San Francisco County, Cal...",2022
79,6075035202,2018,35202.0,352022018,19,6075035202,"Census Tract 352.02, San Francisco County, Cal...",1922
80,6075035300,2018,35300.0,353002018,57,6075035300,"Census Tract 353, San Francisco County, Califo...",2594
81,6075035400,2018,35400.0,354002018,38,6075035400,"Census Tract 354, San Francisco County, Califo...",2594
82,6075040100,2018,40100.0,401002018,57,6075040100,"Census Tract 401, San Francisco County, Califo...",2047
83,6075040200,2018,40200.0,402002018,57,6075040200,"Census Tract 402, San Francisco County, Califo...",2617
84,6075042601,2018,42601.0,426012018,57,6075042601,"Census Tract 426.01, San Francisco County, Cal...",1892
85,6075042700,2018,42700.0,427002018,38,6075042700,"Census Tract 427, San Francisco County, Califo...",2659
86,6075042800,2018,42800.0,428002018,19,6075042800,"Census Tract 428, San Francisco County, Califo...",1031
87,6075045200,2018,45200.0,452002018,38,6075045200,"Census Tract 452, San Francisco County, Califo...",3033
88,6075047600,2018,47600.0,476002018,95,6075047600,"Census Tract 476, San Francisco County, Califo...",2413
89,6075047701,2018,47701.0,477012018,19,6075047701,"Census Tract 477.01, San Francisco County, Cal...",2048
90,6075047702,2018,47702.0,477022018,38,6075047702,"Census Tract 477.02, San Francisco County, Cal...",1699
91,6075047801,2018,47801.0,478012018,19,6075047801,"Census Tract 478.01, San Francisco County, Cal...",1787
92,6075047802,2018,47802.0,478022018,38,6075047802,"Census Tract 478.02, San Francisco County, Cal...",1622
93,6075047901,2018,47901.0,479012018,38,6075047901,"Census Tract 479.01, San Francisco County, Cal...",2819